name: uwu

on:
  workflow_dispatch:

permissions: write-all

jobs:
  upgradeGradleVersion:
    name: Upgrade Gradle Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        JADX_VERSION="1.5.0-dev"
        ./gradlew publishToMavenLocal
    - name: Add updated files to stage 
      run: git add --all 
    - name: Setup email 
      run: git config --global user.email "123667347+ArjunaKumarMohanta@users.noreply.github.com" 
    - name: Setup name 
      run: git config --global user.name "ArjunaKumarMohanta" 
    - name: Commit l 
      run: git commit -m "Upl"
    - name: Push all changes 
      run: git push --force
