name: uwu

on:
  workflow_dispatch:

permissions: write-all

jobs:
  upgradeGradleVersion:
    name: Upgrade Gradle Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew publishToMavenLocal
